from enum import Enum, auto

STATES = [
    # 'Alabama',
    # 'Alaska',
    # 'Arizona',
    # 'Arkansas',
    'California',
    # 'Colorado',
    # 'Connecticut',
    # 'Delaware',
    # 'District of Columbia',
    # 'Florida',
    # 'Georgia',
    # 'Hawaii',
    # 'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    # 'Kansas',
    # 'Kentucky',
    # 'Louisiana',
    # 'Maine',
    # 'Maryland',
    # 'Massachusetts',
    'Michigan',
    'Minnesota',
    # 'Mississippi',
    'Missouri',
    # 'Montana',
    # 'Nebraska',
    # 'Nevada',
    # 'New Hampshire',
    # 'New Jersey',
    # 'New Mexico',
    # 'New York',
    # 'North Carolina',
    # 'North Dakota',
    'Ohio',
    # 'Oklahoma',
    # 'Oregon',
    # 'Pennsylvania',
    # 'Puerto Rico',
    # 'Rhode Island',
    # 'South Carolina',
    # 'South Dakota',
    # 'Tennessee',
    # 'Texas',
    # 'Utah',
    # 'Vermont',
    # 'Virginia',
    # 'Washington',
    # 'West Virginia',
    'Wisconsin'
    # 'Wyoming'
]

CALIFORNIA_COUNTIES = [
    'Alameda',
    'Alpine',
    'Amador',
    'Butte',
    'Calaveras',
    'Colusa',
    'Contra Costa',
    'Del Norte',
    'El Dorado',
    'Fresno',
    'Glenn',
    'Humboldt',
    'Imperial',
    'Inyo',
    'Kern',
    'Kings',
    'Lake',
    'Lassen',
    'Los Angeles',
    'Madera',
    'Marin',
    'Mariposa',
    'Mendocino',
    'Merced',
    'Modoc',
    'Mono',
    'Monterey',
    'Napa',
    'Nevada',
    'Orange',
    'Placer',
    'Plumas',
    'Riverside',
    'Sacramento',
    'San Benito',
    'San Bernardino',
    'San Diego',
    'San Francisco',
    'San Joaquin',
    'San Luis Obispo',
    'San Mateo',
    'Santa Barbara',
    'Santa Clara',
    'Santa Cruz',
    'Shasta',
    'Sierra',
    'Siskiyou',
    'Solano',
    'Sonoma',
    'Stanislaus',
    'Sutter',
    'Tehama',
    'Trinity',
    'Tulare',
    'Tuolumne',
    'Ventura',
    'Yolo',
    'Yuba'
]